esphome:
  name: entrance-media-player-v2
  friendly_name: Entrance Media Player (V2)

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "8WFn4q9ra1FQgOlBHFbYfm9ykDMT1ZAFsKFSvRbUiaI="

ota:
  - platform: esphome
    password: "09206a40a5023c02404931f54e677940"

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  # manual_ip:
  #   static_ip: 192.168.2.129
  #   gateway: 192.168.2.1
  #   subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Entrance-Media-Player-V2"
    password: "yGXtWelob40i"

captive_portal:
    
psram:
  mode: octal
  speed: 80MHz

i2s_audio:
  - id: i2s_bus
    i2s_lrclk_pin: GPIO7
    i2s_bclk_pin: GPIO6

speaker:
  - platform: i2s_audio
    id: i2s_audio_speaker
    i2s_audio_id: i2s_bus
    dac_type: external
    i2s_dout_pin: GPIO5
    sample_rate: 44100
    buffer_duration: 1000ms
    bits_per_sample: 16bit

  - platform: mixer
    id: mixing_speaker
    output_speaker: i2s_audio_speaker
    num_channels: 2
    source_speakers:
      - id: announcement_mixing_input
      - id: media_mixing_input

  - platform: resampler
    id: announcement_resampling_speaker
    output_speaker: announcement_mixing_input
    sample_rate: 44100
  
  - platform: resampler
    id: media_resampling_speaker
    output_speaker: media_mixing_input
    sample_rate: 44100

media_player:
  - platform: speaker
    id: external_media_player
    name: None
    internal: False
    volume_min: 0.4
    volume_max: 0.95
    volume_increment: 0.15
    announcement_pipeline:
      speaker: announcement_resampling_speaker
      format: FLAC
      num_channels: 1 
      sample_rate: 44100
    media_pipeline:
      speaker: media_resampling_speaker
      format: FLAC 
      num_channels: 2
      sample_rate: 44100